pub const ItemKind = enum(u8) {
    survey_blade,
    filter_cloak,
    spark_rod,
    med_gel,
    transit_chart,
    lumen_cell,
    nutrient_paste,
    reed_antitoxin,
    cipher_shard,
    phase_spike,
    signal_mirror,
    ruin_key,
    gravitic_charm,
    machine_scrap,
};

pub const FeatureKind = enum(u8) {
    shelter_beacon,
    fungal_garden,
    sealed_cache,
    survey_pylon,
    scavenger_camp,
    drone_hulk,
    coolant_spring,
    cracked_archive,
    prism_obelisk,
    static_field,
    nanite_bloom,
    collapsed_vault,
    relay_dais,
};

pub const ItemEffect = union(enum) {
    none,
    restore: struct {
        hp: u16 = 0,
        stamina: u16 = 0,
    },
    scan,
    ward,
    cut_hazard,
    unlock,
};

pub const ItemTag = enum(u8) {
    weapon,
    tool,
    medical,
    consumable,
    map,
    ancient_tech,
    key,
    salvage,
    equipment,
};

pub const ItemDef = struct {
    name: []const u8,
    description: []const u8,
    glyph: []const u8,
    stackable: bool,
    consumed_on_use: bool,
    effect: ItemEffect,
    tags: []const ItemTag,
};

pub const FeatureDef = struct {
    name: []const u8,
    description: []const u8,
    glyph: []const u8,
    interaction_hint: []const u8,
    single_use: bool,
};

pub fn itemDef(kind: ItemKind) ItemDef {
    return switch (kind) {
        .survey_blade => .{
            .name = "Survey blade",
            .description = "A ceramic field knife etched with grid coordinates from a dead empire.",
            .glyph = "/",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .none,
            .tags = &.{ .weapon, .tool },
        },
        .filter_cloak => .{
            .name = "Filter cloak",
            .description = "Woven membranes shed dust, spores, and the first bite of bad weather.",
            .glyph = "[",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .ward,
            .tags = &.{ .equipment, .ancient_tech },
        },
        .spark_rod => .{
            .name = "Spark rod",
            .description = "A thumb-length ignition tool that wakes old contacts and field heaters.",
            .glyph = "!",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .cut_hazard,
            .tags = &.{ .tool, .ancient_tech },
        },
        .med_gel => .{
            .name = "Med gel",
            .description = "Silver-blue repair gel sealed in a cracked expedition ampoule.",
            .glyph = "+",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .{ .restore = .{ .hp = 7, .stamina = 1 } },
            .tags = &.{ .medical, .consumable, .ancient_tech },
        },
        .transit_chart => .{
            .name = "Transit chart",
            .description = "A flexible strip of map-film showing stations that no longer exist.",
            .glyph = "?",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .scan,
            .tags = &.{ .map, .ancient_tech },
        },
        .lumen_cell => .{
            .name = "Lumen cell",
            .description = "A warm amber battery that feeds muscles as readily as machines.",
            .glyph = "!",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .{ .restore = .{ .hp = 0, .stamina = 5 } },
            .tags = &.{ .consumable, .ancient_tech },
        },
        .nutrient_paste => .{
            .name = "Nutrient paste",
            .description = "Bland survival paste in foil tubes printed with obsolete safety marks.",
            .glyph = "%",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .{ .restore = .{ .hp = 2, .stamina = 4 } },
            .tags = &.{ .consumable, .medical },
        },
        .reed_antitoxin => .{
            .name = "Reed antitoxin",
            .description = "A bitter green dose used by marsh scouts after spore exposure.",
            .glyph = "!",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .{ .restore = .{ .hp = 4, .stamina = 2 } },
            .tags = &.{ .medical, .consumable },
        },
        .cipher_shard => .{
            .name = "Cipher shard",
            .description = "A triangular memory sliver full of locked pictographs and static.",
            .glyph = "*",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .scan,
            .tags = &.{ .ancient_tech, .salvage },
        },
        .phase_spike => .{
            .name = "Phase spike",
            .description = "A needle tool that can ground unstable fields for a few heartbeats.",
            .glyph = "!",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .cut_hazard,
            .tags = &.{ .tool, .consumable, .ancient_tech },
        },
        .signal_mirror => .{
            .name = "Signal mirror",
            .description = "A polished smart-glass disk that catches invisible patrol beams.",
            .glyph = ")",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .ward,
            .tags = &.{ .tool, .equipment, .ancient_tech },
        },
        .ruin_key => .{
            .name = "Ruin key",
            .description = "A palm-sized access tooth still recognized by some buried locks.",
            .glyph = "&",
            .stackable = true,
            .consumed_on_use = true,
            .effect = .unlock,
            .tags = &.{ .key, .ancient_tech },
        },
        .gravitic_charm => .{
            .name = "Gravitic charm",
            .description = "A humming bead that lightens the pack and steadies climbs.",
            .glyph = "*",
            .stackable = false,
            .consumed_on_use = false,
            .effect = .ward,
            .tags = &.{ .equipment, .ancient_tech },
        },
        .machine_scrap => .{
            .name = "Machine scrap",
            .description = "Useful conductive plates, lenses, and actuator bones.",
            .glyph = "%",
            .stackable = true,
            .consumed_on_use = false,
            .effect = .none,
            .tags = &.{ .salvage, .ancient_tech },
        },
    };
}

pub fn featureDef(kind: FeatureKind) FeatureDef {
    return switch (kind) {
        .shelter_beacon => .{
            .name = "Shelter beacon",
            .description = "A tripod heater blinks beneath a torn survey awning.",
            .glyph = "*",
            .interaction_hint = "Rest inside its low thermal field.",
            .single_use = false,
        },
        .fungal_garden => .{
            .name = "Fungal garden",
            .description = "Pale edible caps grow in the lee of an irrigation ruin.",
            .glyph = "&",
            .interaction_hint = "Harvest careful calories.",
            .single_use = true,
        },
        .sealed_cache => .{
            .name = "Sealed cache",
            .description = "A black supply coffer with a tired but functioning identity latch.",
            .glyph = "C",
            .interaction_hint = "Open the cache.",
            .single_use = true,
        },
        .survey_pylon => .{
            .name = "Survey pylon",
            .description = "A leaning marker projects a fractured route toward the spire.",
            .glyph = "|",
            .interaction_hint = "Read the route memory.",
            .single_use = false,
        },
        .scavenger_camp => .{
            .name = "Scavenger camp",
            .description = "Tarps, quiet cookers, and clipped wire trophies mark a recent claim.",
            .glyph = "A",
            .interaction_hint = "Trade news and search the edges.",
            .single_use = true,
        },
        .drone_hulk => .{
            .name = "Drone hulk",
            .description = "A patrol machine lies split open, its sensor crown still ticking.",
            .glyph = "d",
            .interaction_hint = "Salvage machine parts.",
            .single_use = true,
        },
        .coolant_spring => .{
            .name = "Coolant spring",
            .description = "Clear blue coolant bubbles from ceramic pipework into the mud.",
            .glyph = "~",
            .interaction_hint = "Bottle the clean flow.",
            .single_use = true,
        },
        .cracked_archive => .{
            .name = "Cracked archive",
            .description = "Shelf-walls of glass memory stand exposed to weather and lichen.",
            .glyph = "?",
            .interaction_hint = "Search for readable shards.",
            .single_use = true,
        },
        .prism_obelisk => .{
            .name = "Prism obelisk",
            .description = "An impossible needle of lens-stone splits daylight into cold symbols.",
            .glyph = "!",
            .interaction_hint = "Align a signal mirror or study the glare.",
            .single_use = false,
        },
        .static_field => .{
            .name = "Static field",
            .description = "Blue-white charge crawls over the ground in a broken warning grid.",
            .glyph = "x",
            .interaction_hint = "Ground it with old tech or force a passage.",
            .single_use = true,
        },
        .nanite_bloom => .{
            .name = "Nanite bloom",
            .description = "Silver dust flowers pulse around a buried maintenance wound.",
            .glyph = "%",
            .interaction_hint = "Skim useful motes before they bite.",
            .single_use = true,
        },
        .collapsed_vault => .{
            .name = "Collapsed vault",
            .description = "A half-sunk access chamber shows ribs of alloy under fallen stone.",
            .glyph = "V",
            .interaction_hint = "Force or unlock the vault seam.",
            .single_use = true,
        },
        .relay_dais => .{
            .name = "Relay dais",
            .description = "A circular platform hums with packets meant for vanished receivers.",
            .glyph = "O",
            .interaction_hint = "Tune the relay and listen.",
            .single_use = false,
        },
    };
}
